www_tatoeba/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^www_tatoeba/', include('www_tatoeba.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    # Tatoeba url
    (r'^\w+/?$', 'views.index.index'),
    (r'^\w+/home/?$', 'views.index.home'),
    (r'^\w+/users/check_login/?$', 'views.users.check_login'),
    (r'^\w+/users/logout/?$', 'views.users.logout'),
    (r'^\w+/users/login/?$', 'views.users.login'),
    (r'^\w+/users/new_password/?$', 'views.users.new_password'),
    (r'^\w+/users/all/?$', 'views.users.all'),
    (r'^\w+/users/register/?$', 'views.users.register'),
    (r'^\w+/sentences/show/random/?$', 'views.sentences.random'),
    url(r'^(\w+)/sentences/show/(?P<sentence_id>\d+)/?$', 'views.sentences.show', name="sentences-show"),
)

www_tatoeba/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)
	remember = forms.BooleanField(required=False)
class RegisterForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)
	email = forms.EmailField()
	captcha = forms.CharField()
	termsOfUse = forms.BooleanField()

www_tatoeba/views/user.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as dlogout

def check_login(request, language):
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(username=username, password=password)
	if user is not None:
		if user.is_active:
			login(request, user)
			msg = 'login'
		else:
			msg = 'disabled'
	else:
		msg = 'wrong'
	t = loader.get_template('pages/index.html')
	c = RequestContext(request, {})
	return HttpResponse(msg)

def logout(request, language):
	dlogout(request)
	return HttpResponse('Adieux')

www_tatoeba/views/users.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.template import RequestContext, loader
from django.contrib.auth import authenticate
from django.contrib.auth import login as dlogin
from django.contrib.auth import logout as dlogout


def check_login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            dlogin(request, user)
            msg = 'login'
        else:
            msg = 'disabled'
    else:
        msg = 'wrong'
    t = loader.get_template('pages/index.html')
    c = RequestContext(request, {})
    return HttpResponseRedirect('/home')


def logout(request):
    dlogout(request)
    return HttpResponseRedirect('/users/login')


def all(request):
    from www_tatoeba.models import AuthUser
    allUsers = AuthUser.objects.all()
    t = loader.get_template('users/all.html')
    c = RequestContext(request, {
        'allUsers': allUsers
    })
    return HttpResponse(t.render(c))


def register(request):
    from www_tatoeba.forms import RegisterForm
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            from django.contrib.auth.models import User
            user = User.objects.create_user(
                form.cleaned_data['username'],
                form.cleaned_data['email'],
                form.cleaned_data['password']
            )
            return HttpResponseRedirect('/users/login')
    else:
        form = RegisterForm()

    t = loader.get_template('users/register.html')
    c = RequestContext(request, {'form': form})
    return HttpResponse(t.render(c))


def login(request):
    from www_tatoeba.forms import LoginForm
    if request.method == 'POST':
        form = LoginForm(request.POST)
    else:
        form = LoginForm()
    t = loader.get_template('users/login.html')
    c = RequestContext(request, {'form': form})
    return HttpResponse(t.render(c))


def new_password(request):
    #from www_tatoeba.models import AuthUser
    #user = AuthUser.objects.get(email='biptaste@gmail.com')
    t = loader.get_template('users/new_password.html')
    c = RequestContext(request, {})
    return HttpResponse(t.render(c))

www_tatoeba/templates/users/all.html
{% extends "layouts/base.html" %}

{% block title %}plop{% endblock %}

{% block content %}
<div id="main_content">
	<table class="users">
		<tbody>
			<tr>
				<th></th>
				<th>Username</th>
				<th>Member since</th>
				<th>Last login</th>
				<th>Member status</th>
			</tr>
			{% for u in allUsers %}
			<tr>
				<td></td>
				<td>{{ u.username }}</td>
				<td>{{ u.date_joined }}</td>
				<td>{{ u.last_login }}</td>
				<td></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}

www_tatoeba/templates/users/login.html
{% extends "layouts/base.html" %}

{% block title %}plop{% endblock %}
{% block header %}
<link rel="stylesheet" type="text/css" href="/static/css/users/login.css">
{% endblock %}
{% block content %}
<form id="UserLoginForm" method="post" action="/{{ LANGUAGE_CODE }}/users/check_login"> {% csrf_token %}
<div>
	<label for="id_username">Username :</label>
	{{ form.username }}
</div>
<div>
	<label for="id_password">Password :</label>
	{{ form.password }}
</div>
<div>
	{{ form.remember }}
	<label for="id_remember">Remember me</label>
</div>
<div class="submit">
	<input type="submit" value="Log in">
</div>
</form>
<div id="PasswordForgotten">
	<a href="/{{ LANGUAGE_CODE }}/users/new_password">Password forgotten?</a>
</div>
<div id="ClickHereToRegister">
	<a href="/{{ LANGUAGE_CODE }}/users/register" class="registerButton">Register</a>
</div>
{% endblock %}

www_tatoeba/templates/users/new_password.html
{% extends "layouts/base.html" %}

{% block title %}plop{% endblock %}

{% block content %}
<h2>Send new password</h2>
<form id="UserNewPasswordForm" method="post" action="/{{ LANGUAGE_CODE }}/users/new_password">
</form>
{% endblock %}

www_tatoeba/templates/users/register.html
{% extends "layouts/base.html" %}

{% block title  %}plop{% endblock %}
{% block header %}
<link rel="stylesheet" type="text/css" href="/static/css/users/register.css" />
{% endblock %}

{% block content %}
<form id="UserRegisterForm" action="/{{ LANGUAGE_CODE }}/users/register" method="post"> {% csrf_token %}
	<table id="userInformation">
		<tr>
			<td class="field"><label for="id_username">Username :</label></td>
			<td>{{ form.username }}</td>
		</tr>
		<tr>
			<td class="field"><label for="id_password">Password :</label></td>
			<td>{{ form.password }}</td>
		</tr>
		<tr>
			<td class="field"><label for="id_email">Email :</label></td>
			<td>{{ form.email }}</td>
		</tr>
	</table>
	<div id="quiz">
		We need to make sure are human.
		<label for="id_">What are the five first letters of your email?</label>
		{{ form.captcha }}
	</div>
	<div id="termsOfUse">
		{{ form.termsOfUse }}
		I accept the <a href=""> terms of use</a>
	</div>
	<input id="registerButton" type="submit" value="Register">
</form>
{% endblock %}